/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/18f9c0e1-995e-49b2-a275-9deba2241b1d

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool relay1;
  bool relay2;
  bool relay3;
  bool relay4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

// numbers are weird but on esp32 they're beside each other
int relayPin1 = 33;
int relayPin2 = 32;
int relayPin3 = 26;
int relayPin4 = 25;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);

  // pin modes
  pinMode(relayPin1, OUTPUT);
  pinMode(relayPin2, OUTPUT);
  pinMode(relayPin3, OUTPUT);
  pinMode(relayPin4, OUTPUT);
  
  // default off
  digitalWrite(relayPin1, HIGH);
  digitalWrite(relayPin2, HIGH);
  digitalWrite(relayPin3, HIGH);
  digitalWrite(relayPin4, HIGH);

  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here

  // delay(1000);
  // digitalWrite(pinNum, HIGH);
  // delay(1000);
  // digitalWrite(pinNum, LOW);
  // serial.write("UPDATED 1")


}

/*
  Since Relay1 is READ_WRITE variable, onRelay1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay1Change()  {
  // Add your code here to act upon Relay1 change
  digitalWrite(relayPin1, relay1 ? LOW : HIGH);
}


/*
  Since Relay2 is READ_WRITE variable, onRelay2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay2Change()  {
  // Add your code here to act upon Relay2 change
  digitalWrite(relayPin2, relay2 ? LOW : HIGH);
}

/*
  Since Relay3 is READ_WRITE variable, onRelay3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay3Change()  {
  // Add your code here to act upon Relay3 change
  digitalWrite(relayPin3, relay3 ? LOW : HIGH);
}

/*
  Since Relay4 is READ_WRITE variable, onRelay4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRelay4Change()  {
  // Add your code here to act upon Relay4 change
  digitalWrite(relayPin4, relay4 ? LOW : HIGH);
}

